### ISSUE TITLE
Input 输入框 autofocus报错

### ISSUE THREAD

**Issue by tsliangyonghui** [nutui-uniapp/nutui-uniapp#39]
### uniapp-nutui 版本号

1.0.0

### 平台

h5

### 重现链接

<nut-input v-model="newPassword" placeholder="" autofocus />

### 重现步骤

use-transition.ts:137 Uncaught (in promise) TypeError: inputRef.value.focus is not a function
    at input.vue:170:20
    at vue.runtime.esm.js:4109:40
    at callWithErrorHandling (vue.runtime.esm.js:1375:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1384:21)
    at hook.__weh.hook.__weh (vue.runtime.esm.js:4083:29)
    at flushPostFlushCbs (vue.runtime.esm.js:1562:47)
    at flushJobs (vue.runtime.esm.js:1616:9)

### 期望的结果是什么？

input组件没有获取焦点

### 实际的结果是什么？

input组件能获取焦点

**Comment by yang1206** [comment]
1.1.1已修复
